modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = ""

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "logo.png"
credits = "CSX8600 Base Code. KillerMapper for making this the first time and creating many of the wonderful road sign textures. The_Epicness9000, Alex9327, RavenholmZombie, South Texas Railfan for community sign submissions."

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "immersiverailroading"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "computercraft"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
